# Generated by Django 5.2 on 2025-04-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_no', models.IntegerField()),
                ('classroom_name', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAsset',
            fields=[
                ('classroom_asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('inactive_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_asset.classroom')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_asset.registeredasset')),
            ],
        ),
    ]
